dist: trusty
sudo: require

language: cpp
compiler: clang++

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - cmake-data
      - cmake
      - python3
      - python3-dev
      - python3-venv
      - python3-pip

matrix:
  include:
    # works on Trusty
    - os: linux
      env: PYTHON=3.5
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - pyenv shell 3.5
    - pip3 install --user --upgrade pip3 virtualenv
    - virtualenv -p python3.5 venv
    - source venv/bin/activate


install:
    - python3 setup.py sdist
    - pip3 install --verbose dist/*.tar.gz

script:
  - CXX=/usr/bin/clang++-5.0
  - cd ${TRAVIS_BUILD_DIR}/Software
  - bash dependencies.sh 
  - cd ${TRAVIS_BUILD_DIR}
  - cd Software/
  - mkdir build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../src
  - make all -j
  - ctest --output-on-failure
  - make clean
  - cmake -DCMAKE_BUILD_TYPE=Release ../src
  - make -j
